FROM public.ecr.aws/docker/library/python:3.13

WORKDIR /emulator
# Install Hatch
RUN pip install --no-cache-dir hatch

# Copy project files
COPY . .

# install emulator
RUN hatch run pip install -e .

# where is the hatch executable installed
RUN where hatch

# enable hatch executable
RUN chmod +x /usr/local/bin/hatch

CMD ["/usr/local/bin/hatch", "run", "durable-functions-emulator", "--host", "0.0.0.0", "--port", "9014"]