FROM python:3.13-slim

WORKDIR /emulator
# Install Hatch
RUN pip install --no-cache-dir hatch

# Copy project files
COPY . .

# install emulator
RUN hatch run pip install -e .

CMD ["hatch", "run", "durable-functions-emulator", "--host", "0.0.0.0", "--port", "9014"]