AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.13
    Timeout: 60
    MemorySize: 128
    Environment:
      Variables:
        AWS_ENDPOINT_URL_LAMBDA:
          Ref: LambdaEndpoint
Parameters:
  LambdaEndpoint:
    Type: String
    Default: https://lambda.us-west-2.amazonaws.com
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: hello_world.handler
      Description: A simple hello world example with no durable operations
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  Step:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: step.handler
      Description: Basic usage of context.step() to checkpoint a simple operation
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  StepWithName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: step_with_name.handler
      Description: Step operation with explicit name parameter
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  StepWithRetry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: step_with_retry.handler
      Description: Usage of context.step() with retry configuration for fault tolerance
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  Wait:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: wait.handler
      Description: Basic usage of context.wait() to pause execution
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  Callback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: callback.handler
      Description:
        Basic usage of context.create_callback() to create a callback for
        external systems
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  WaitForCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: wait_for_callback.handler
      Description:
        Usage of context.wait_for_callback() to wait for external system
        responses
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  RunInChildContext:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: run_in_child_context.handler
      Description:
        Usage of context.run_in_child_context() to execute operations in
        isolated contexts
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  Parallel:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: parallel.handler
      Description: Executing multiple durable operations in parallel
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  MapOperations:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: map_operations.handler
      Description: Processing collections using map-like durable operations
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  BlockExample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: block_example.handler
      Description: Nested child contexts demonstrating block operations
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  LoggerExample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: logger_example.handler
      Description: Demonstrating logger usage and enrichment in DurableContext
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  StepsWithRetry:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: steps_with_retry.handler
      Description: Multiple steps with retry logic in a polling pattern
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
  WaitForCondition:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: wait_for_condition.handler
      Description: Polling pattern that waits for a condition to be met
      DurableConfig:
        RetentionPeriodInDays: 7
        ExecutionTimeout: 300
